=== revanfall/lr5StaxCurs/src/main/resources/lr5.dtd
<?xml encoding="UTF-8"?>

        <!ELEMENT CATALOG (CD)+>
        <!ATTLIST CATALOG
                xmlns CDATA #FIXED ''>

        <!ELEMENT CD (TITLE,ARTIST,COUNTRY,(COMPANY|COMPNY),PRICE,YEAR)>
        <!ATTLIST CD
                xmlns CDATA #FIXED ''
                id CDATA #REQUIRED>

        <!ELEMENT TITLE (#PCDATA)>
        <!ATTLIST TITLE
                xmlns CDATA #FIXED ''>

        <!ELEMENT ARTIST (#PCDATA)>
        <!ATTLIST ARTIST
                xmlns CDATA #FIXED ''>

        <!ELEMENT COUNTRY (#PCDATA)>
        <!ATTLIST COUNTRY
                xmlns CDATA #FIXED ''>

        <!ELEMENT COMPANY (#PCDATA)>
        <!ATTLIST COMPANY
                xmlns CDATA #FIXED ''>

        <!ELEMENT COMPNY (#PCDATA)>
        <!ATTLIST COMPNY
                xmlns CDATA #FIXED ''>

        <!ELEMENT PRICE (#PCDATA)>
        <!ATTLIST PRICE
                xmlns CDATA #FIXED ''>

        <!ELEMENT YEAR (#PCDATA)>
        <!ATTLIST YEAR
                xmlns CDATA #FIXED ''>

=== revanfall/lr5StaxCurs/src/main/resources/lr5xml.xml
<?xml version="1.0"?>
<!DOCTYPE CATALOG SYSTEM "lr5.dtd">
<CATALOG>
    <CD id="1">
        <TITLE>Empire Burlesque</TITLE>
        <ARTIST>Bob Dylan</ARTIST>
        <COUNTRY>USA</COUNTRY>
        <COMPANY>Columbia</COMPANY>
        <PRICE>10.90</PRICE>
        <YEAR>-2051</YEAR>
    </CD>
    <CD id="2">
        <TITLE>Romanza</TITLE>
        <ARIST>Andrea Bocelli</ARIST>
        <COUNTRY>EU</COUNTRY>
        <COMPANY>Polydor</COMPANY>
        <PRICE>10.80</PRICE>
        <YEAR>1996</YEAR>
    </CD>
</CATALOG>
